#!/usr/bin/env pythono3
"""
Async Comprehensions
"""
import asyncio
import random


async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> list[float]:
    """
    collects 10 random numbers generated by
    `async_generator`
    """

    return [i async for i in async_generator()]
